### ISSUE TITLE
analysis-explorer master doesn't compile with analysis-net master

### ISSUE THREAD

**Issue by mogulano** [edgardozoppi/analysis-explorer#1]
Hi, tried to build the project, but analysis-explorer master doesn't compile with analysis-net master. Then I noticed there are many branches in each project. Are these different features? Which one is the most stable and not obsolete?

**Comment by edgardozoppi** [comment]
Hi, you are right. Master branches have to be updated or removed in both repos, they are pretty old. I recommend using branch `advanced-pta` of the `analysis-net` repo and branch `using-graphx` of the `analysis-explorer` repo. They have all the latest features and bug fixes and should work fine together.

There are also other branches with some experimental features as follows:

**Both repos**
- `java-support` to also support loading Java executables (JARs). So far it only loads all the metadata but not the bytecode of the methods. It is still a work in progress.
- `metadata-provider` to load .NET assemblies using the Microsoft official and more performant [reflection metadata](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata) library.

**`analysis-net` repo**
- `cci-version` this is the original deprecated version that was completely coupled to CCI. I don't recommend using it unless you are already using CCI in your project and want to start using the `analysis-net` repo.
- `exceptional-cfa` to better support control-flow of exception handlers like `try`, `catch`, `finally`.

**`analysis-explorer` repo**
- `vs-extension` this is a Visual Studio extension that adds contextual menus to the Class Viewer tool window to execute Analysis Explorer features from within the IDE.

**Comment by mogulano** [comment]
Thanks for the explanation!
